---
title: "vidéos à analyser"
format: 
  html:
    title-block-banner: "#ee1a26"
    embed-resources: false
css: "../monstyle.css"  
---

L'actualité est toujours aussi chaude sur le front ukrainien.
J'ai extrait de Twitter des vidéos virales mais les twittos qui qualifient ces vidéos disent des choses contradictoires. 
Il va falloir que vous vérifiez vous-même de quoi il s'agit. 
Attention : il y a beaucoup de gens qui veulent faire du buzz en twittant confortablement installés dans leurs fauteuils des vidéos de guerres anciennes.
Ne vous faites pas avoir !

Les vidéos en question ont pour noms de fichiers

- [bataille_rue.mp4](https://video.univ-rennes1.fr/downloads/file/v12689c0f3e505kmy98b/?url=media_540_Sg9xERZLMU.mp4)

```{=html}
<iframe width="720" height="530" src="https://video.univ-rennes1.fr/permalink/v12689c0f3e505kmy98b/iframe/" allowfullscreen="allowfullscreen" allow="autoplay"></iframe>
```

Il semble d'après la personne qui l'a postée sur Twitter que cette vidéo montre **l'avancée des troupes Russes à Severodonesk**

- [bombardement.mp4](https://video.univ-rennes1.fr/downloads/file/v12689c0f3e9fjjk2pjy/?url=media_360_NoDVITyx9t.mp4)

```{=html}
<iframe width="720" height="530" src="https://video.univ-rennes1.fr/permalink/v12689c0f3e9fjjk2pjy/iframe/" allowfullscreen="allowfullscreen" allow="autoplay"></iframe>
```

Le compte qui l'a posté indiquait que c'était une **vidéo prise le 26 avril 2022 à Kyev** par l'un de ses amis

- [tir_roquettes.mp4](https://video.univ-rennes1.fr/downloads/file/v12689c0f3ef06p2av7i/?url=media_720_raRuD83kJi.mp4)

```{=html}
<iframe width="720" height="530" src="https://video.univ-rennes1.fr/permalink/v12689c0f3ef06p2av7i/iframe/" allowfullscreen="allowfullscreen" allow="autoplay"></iframe>
```

Il s'agirait d'**images prises sur le terrain par une chaîne de télévision ukrainienne du côté de Kharkiv**

Ah et ça s'agite aussi au Vénézuela apparamment. Je vous laisse aussi la vidéo [emeute.mp4](https://video.univ-rennes1.fr/downloads/file/v1264071880cfzucp9lt/?url=media_720_oEtnlAWWkl.mp4) à analyser.

```{=html}
<iframe width="720" height="530" src="https://video.univ-rennes1.fr/permalink/v1264071880cfzucp9lt/iframe/" allowfullscreen="allowfullscreen" allow="autoplay"></iframe>
```

Il semble que cela se passe à Caracas, mais pas eu le temps de checker. 
Je vous laisse le soin de le faire. 

Ma femme m'a envoyé un nouveau coup de fil : les enfants et elle sont bien à l'abri et le feu est heureusement limité à la charpente (allez savoir ce qui s'est passé)
Il faut quand même que j'y ailler pour constater et les rassurer. 
ça promet une belle journée. 

Désolé pour le taf à faire et bon courage à vous, je sais que l'heure du bouclage est proche !